# Generated by Django 4.2.24 on 2025-11-13 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de commande')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('shipping_address', models.TextField(verbose_name='Adresse de livraison')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Ville')),
                ('shipping_postal_code', models.CharField(max_length=20, verbose_name='Code postal')),
                ('shipping_country', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('payment_method', models.CharField(default='paypal', max_length=20, verbose_name='Méthode de paiement')),
                ('payment_status', models.CharField(default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('paypal_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('processing', 'En préparation'), ('shipped', 'Expédié'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expédition")),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Notes du client')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Notes admin')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('goodies', 'Goodies DFD'), ('artisanat', 'Artisanat Local'), ('livres', 'Livres & Publications'), ('cadeaux', 'Cadeaux Solidaires')], max_length=20, verbose_name='Catégorie')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Image')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Don', 'verbose_name_plural': 'Dons'},
        ),
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text='Don anonyme', verbose_name='Anonyme'),
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, help_text='Message du donateur', null=True, verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('card', 'Carte bancaire'), ('virement', 'Virement'), ('other', 'Autre')], default='paypal', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_payer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Payeur PayPal'),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date paiement PayPal'),
        ),
        migrations.AddField(
            model_name='donation',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transaction PayPal'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(max_length=254, verbose_name='Email du donateur'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(max_length=100, verbose_name='Nom du donateur'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
